name = "okex-trader-tracker-worker"
main = "workers/collector.ts"
compatibility_date = "2024-09-23"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "okex-trader-db"
database_id = "b3b71ad8-c7c1-4f92-a017-6f6ebd9a3e78"

[triggers]
crons = ["*/5 * * * *"] # Every 5 minutes

[observability]
enabled = true
